INSERT INTO subscription_plans (
    name,
    price_per_period,
    period_days,
    base_contact_limit,
    booster_price,
    booster_contacts,
    casting_post_price,
    casting_post_days,
    premium_profile_price,
    premium_profile_days,
    active
)
SELECT
    'Promo 30 days',
    0,
    30,
    100,
    500,
    10,
    1000,
    14,
    1500,
    30,
    false
WHERE NOT EXISTS (
    SELECT 1 FROM subscription_plans WHERE name = 'Promo 30 days'
);

CREATE TABLE IF NOT EXISTS promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    contact_limit INTEGER NOT NULL DEFAULT 100,
    duration_days INTEGER NOT NULL DEFAULT 30,
    active BOOLEAN NOT NULL DEFAULT true,
    expires_at TIMESTAMP,
    used_by_customer_id BIGINT,
    subscription_id BIGINT,
    used_at TIMESTAMP,
    created_at TIMESTAMP
);

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS code VARCHAR(255);

ALTER TABLE promo_codes
    ALTER COLUMN code SET NOT NULL;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS description VARCHAR(255);

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS contact_limit INTEGER;

UPDATE promo_codes
SET contact_limit = 100
WHERE contact_limit IS NULL;

ALTER TABLE promo_codes
    ALTER COLUMN contact_limit SET DEFAULT 100;

ALTER TABLE promo_codes
    ALTER COLUMN contact_limit SET NOT NULL;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS duration_days INTEGER;

UPDATE promo_codes
SET duration_days = 30
WHERE duration_days IS NULL;

ALTER TABLE promo_codes
    ALTER COLUMN duration_days SET DEFAULT 30;

ALTER TABLE promo_codes
    ALTER COLUMN duration_days SET NOT NULL;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS active BOOLEAN;

UPDATE promo_codes
SET active = true
WHERE active IS NULL;

ALTER TABLE promo_codes
    ALTER COLUMN active SET DEFAULT true;

ALTER TABLE promo_codes
    ALTER COLUMN active SET NOT NULL;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS used_by_customer_id BIGINT;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS subscription_id BIGINT;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS used_at TIMESTAMP;

ALTER TABLE promo_codes
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

UPDATE promo_codes
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_promo_codes_code
    ON promo_codes (code);

CREATE INDEX IF NOT EXISTS idx_promo_codes_used_by_customer
    ON promo_codes (used_by_customer_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_promo_codes_subscription
    ON promo_codes (subscription_id)
    WHERE subscription_id IS NOT NULL;

INSERT INTO promo_codes (code, description, contact_limit, duration_days, active, created_at)
VALUES
    ('CUST-FREE-0001', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0002', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0003', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0004', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0005', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0006', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0007', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0008', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0009', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0010', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0011', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0012', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0013', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0014', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0015', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0016', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0017', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0018', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0019', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0020', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0021', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0022', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0023', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0024', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0025', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0026', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0027', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0028', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0029', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0030', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0031', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0032', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0033', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0034', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0035', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0036', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0037', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0038', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0039', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0040', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0041', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0042', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0043', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0044', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0045', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0046', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0047', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0048', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0049', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP),
    ('CUST-FREE-0050', 'Customer free trial: 100 contacts for 30 days', 100, 30, true, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
